#.libPaths( c( .libPaths(), '/home/boris/R/x86_64-pc-linux-gnu-library/4.1/') )
#library(Seurat)
library(dittoSeq)
library(plotly)
library(shiny)
library(shinybusy)
library(shinyWidgets)
library(shinydashboard)
library(dashboardthemes)

#library(shinyjs)
#library(dplyr)
#library(SingleR)
#library(stringr)
#library(celldex)
#library(monocle)
#library(escape)