---
title: "Rapport patient"
html_document: default
output:
  pdf_document: default
  word_document: default
params:
  output_dir: NA
  patient: NA
---

```{r setup, include=FALSE}
library(png)
```

# `r params$patient`

## Métadonnées : 
```{r Sunburst, echo=FALSE}
grid::grid.raster(readPNG(paste0("/home/boris/Bureau/scShiny/www/", params$patient,"/metadata_", params$patient,"_1.png")))
```


## ACP : 
```{r ACP, echo=FALSE}
grid::grid.raster(readPNG(paste0("/home/boris/Bureau/scShiny/www/", params$patient,"/ACP_", params$patient,"_1.png")))
```

## VDJ : 
```{r VDJ, echo=FALSE}
#grid::grid.raster(readPNG(paste0("/home/boris/Bureau/scShiny/www/", params$patient,"/VDJ_", params$patient,"_1.png")))
```


## Clonotype : 
```{r Clonotype, echo=FALSE}
grid::grid.raster(readPNG(paste0("/home/boris/Bureau/scShiny/www/", params$patient,"/clonotype_", params$patient,"_1.png")))
```

## V :
```{r V, echo=FALSE}
grid::grid.raster(readPNG(paste0("/home/boris/Bureau/scShiny/www/", params$patient,"/V_", params$patient,"_1.png")))
```

## D : 
```{r D, echo=FALSE}
grid::grid.raster(readPNG(paste0("/home/boris/Bureau/scShiny/www/", params$patient,"/D_", params$patient,"_1.png")))
```

## J : 
```{r J, echo=FALSE}
grid::grid.raster(readPNG(paste0("/home/boris/Bureau/scShiny/www/", params$patient,"/J_", params$patient,"_1.png")))
```

## Heavy : 
```{r Heavy, echo=FALSE}  
grid::grid.raster(readPNG(paste0("/home/boris/Bureau/scShiny/www/", params$patient,"/Heavy_", params$patient,"_1.png")))
```

```{r HeavyD, echo=FALSE}  
grid::grid.raster(readPNG(paste0("/home/boris/Bureau/scShiny/www/", params$patient,"/Isotype_", params$patient,"_1.png")))
```

## Light : 
```{r Light, echo=FALSE}  
grid::grid.raster(readPNG(paste0("/home/boris/Bureau/scShiny/www/", params$patient,"/Light_", params$patient,"_1.png")))
```

```{r LightD, echo=FALSE}  
grid::grid.raster(readPNG(paste0("/home/boris/Bureau/scShiny/www/", params$patient,"/Type_", params$patient,"_1.png")))
```
