---
title: "Rapport Patient FL08G0293"
html_document: default
---

```{r setup, include=FALSE}
library(Seurat)
library(monocle)
library(escape)
library(dittoSeq)
library(plotly)
library(dplyr)
library(shiny)
library(shinyjs)
library(shinybusy)
library(shinyWidgets)
library(shinydashboard)
library(dashboardthemes)
library(flexdashboard)
load(file = "/home/boris/Documents/analyse/singlet_FL08G0293.RData")
singlet <- all
```


```{r eruptions, echo=FALSE}

```

## MĂ©tadonnĂ©es : 

```{r Sunburst, echo=FALSE}
renderPlotly({
  plot_ly(singlet@tools$sunburst, ids = ~ids ,labels = ~labels, parents = ~parents, values = ~values, marker = list(colors = c( "#BEBADA", "#8DD3C7", "#FB8072", "#80B1D3", "#FDB462")),
            type = 'sunburst', branchvalues = 'total', hoverinfo = "text", hovertext = paste(singlet@tools$sunburst$labels, ":", round((singlet@tools$sunburst$values/singlet@tools$sunburst$values[1])*100,2),"%", "\nTotal : " ,singlet@tools$sunburst$values)) 
  })
```

## Clonotype : 

```{r Clonotype, echo=FALSE}
renderPlotly({
  ## -- Clonotype -- ##
  plot_ly(x = singlet@tools$Clonotype[[1]], y = singlet@tools$Clonotype[[2]], name = "Info", type = "bar", 
            hovertemplate = paste0('Clonotype : %{x}\n', "Proportion : ", round(singlet@tools$vloupe$proportion[1:5],3)*100,
                                   "% \nType : ", singlet@tools$vloupe$type[1:5], 
                                   "\nIsotype : ", singlet@tools$vloupe$igh_c_genes[1:5], 
                                   "\nHeavy : ", singlet@tools$vloupe$V_lourde[1:5], " / ", singlet@tools$vloupe$D_lourde[1:5], " / ", singlet@tools$vloupe$J_lourde[1:5], 
                                   "\nLight : ", singlet@tools$vloupe$V_legere[1:5], " / ", singlet@tools$vloupe$J_legere[1:5])) %>% layout(title='Frequencies of the mains clonotypes', yaxis =list(title="Number of cells"))
})
```

## VDJ : 

```{r VDJ, echo=FALSE}
## -- VDJ -- ##
renderPlotly({
  plot_ly(x = singlet@tools$V[[1]], y = singlet@tools$V[[2]], name = "Clonotype", type = "bar") %>% 
    layout(title='Frequencies V genes : Heavy and Lights chains', xaxis = list(tickangle = 45), yaxis =list(title="Number of cells"))
})
renderPlotly({
  plot_ly(x = singlet@tools$D[[1]], y = singlet@tools$D[[2]], name = "Clonotype", type = "bar") %>% 
    layout(title='Frequencies D genes : Heavy chain',xaxis = list(tickangle = 45), yaxis =list(title="Number of cells"))
})
renderPlotly({
  singlet
  plot_ly(x = singlet@tools$J[[1]], y = singlet@tools$J[[2]], name = "Clonotype", type = "bar") %>% 
    layout(title='Frequencies J genes : Heavy and Lights chains',xaxis = list(tickangle = 45), yaxis =list(title="Number of cells"))
})
```

## Heavy : 

```{r Heavy, echo=FALSE}  
## -- Heavy chain -- ##
renderPlotly({
  plot_ly(x = singlet@tools$Heavy[[1]], y = singlet@tools$Heavy[[2]], name = "Heavy Chain", type = "bar",
          hovertemplate = paste0("Locus : %{x}\nProportion : ", round(singlet@tools$Heavy[[2]]/sum(singlet@tools$Heavy[[2]]),3)*100,"%")) %>%  
    layout(title='Frequencies Heavy Chain' , xaxis = list(tickangle = 45), yaxis =list(title="Number of cells"))
})
renderPlotly({
  plot_ly(x = singlet@tools$Isotype[[1]], y = singlet@tools$Isotype[[2]], name = "Heavy Chain", type = "bar",
          hovertemplate = paste0("Locus : %{x}\nProportion : ", round(singlet@tools$Isotype[[2]]/sum(singlet@tools$Isotype[[2]]),3)*100,"%")) %>%  
    layout(title='Frequencies Heavy Chain with details' , xaxis = list(tickangle = 45), yaxis =list(title="Number of cells"))
})
```

## Light : 

```{r Light, echo=FALSE}  
## -- Light chain -- ##
renderPlotly({
  plot_ly(x = singlet@tools$Light[[1]], y = singlet@tools$Light[[2]], name = "Light Chain", type = "bar",
          hovertemplate = paste0("Locus : %{x}\nProportion : ", round(singlet@tools$Light[[2]]/sum(singlet@tools$Light[[2]]),3)*100,"%")) %>% 
    layout(title='Frequencies Light Chain',yaxis =list(title="Number of cells"))
})
renderPlotly({
  plot_ly(x = singlet@tools$Type[[1]], y = singlet@tools$Type[[2]], name = "Clonotype", type = "bar",
          hovertemplate = paste0("Locus : %{x}\nProportion : ", round(singlet@tools$Type[[2]]/sum(singlet@tools$Type[[2]]),3)*100,"%")) %>% 
    layout(title='Frequencies Light Chain with details', yaxis =list(title="Number of cells"))
})
```


